[build]
  command = "npm run build"
  functions = "functions"
  public = "public"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index"
  status = 200

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"